// .bkp/market/src/components/KwamiGlassButton.tsx
import { useEffect, useMemo, useRef } from 'react'
import { createGlassButton } from 'kwami/ui'

export function KwamiGlassButton(props: {
  label: string
  mode?: 'primary' | 'ghost' | 'outline'
  size?: 'sm' | 'md' | 'lg'
  disabled?: boolean
  block?: boolean
  onClick?: (event: MouseEvent) => void
}) {
  const mountRef = useRef<HTMLDivElement | null>(null)
  const handleRef = useRef<ReturnType<typeof createGlassButton> | null>(null)
  const key = useMemo(() => `${props.mode ?? 'primary'}:${props.size ?? 'md'}:${props.block ? '1' : '0'}`, [props.block, props.mode, props.size])

  useEffect(() => {
    const mount = mountRef.current
    if (!mount) return

    mount.innerHTML = ''
    handleRef.current?.element?.remove()

    const handle = createGlassButton({
      label: props.label,
      mode: props.mode ?? 'primary',
      size: props.size ?? 'md',
      disabled: !!props.disabled,
      onClick: (e) => props.onClick?.(e),
    })

    if (props.block) handle.element.style.width = '100%'

    handleRef.current = handle
    mount.appendChild(handle.element)

    return () => {
      handleRef.current?.element?.remove()
      handleRef.current = null
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key])

  useEffect(() => {
    handleRef.current?.setLabel(props.label)
    handleRef.current?.setDisabled(!!props.disabled)
  }, [props.disabled, props.label])

  return <div ref={mountRef} className={['inline-flex', props.block ? 'w-full' : ''].filter(Boolean).join(' ')} />
}

// candy/src/components/KwamiGlassButton.vue
<template>
  <div ref="mount" class="inline-flex" :class="block ? 'w-full' : ''" />
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { createGlassButton } from 'kwami/ui'

const emit = defineEmits<{
  (e: 'click', event: MouseEvent): void
}>()

const props = withDefaults(
  defineProps<{
    label: string
    mode?: 'primary' | 'ghost' | 'outline'
    size?: 'sm' | 'md' | 'lg'
    disabled?: boolean
    block?: boolean
  }>(),
  {
    mode: 'primary',
    size: 'md',
    disabled: false,
    block: false,
  }
)

const mount = ref<HTMLDivElement | null>(null)
let handle: ReturnType<typeof createGlassButton> | null = null

const rebuild = () => {
  if (!mount.value) return
  mount.value.innerHTML = ''

  handle = createGlassButton({
    label: props.label,
    mode: props.mode,
    size: props.size,
    disabled: props.disabled,
    onClick: (event) => emit('click', event),
  })

  if (props.block) {
    handle.element.style.width = '100%'
  }

  mount.value.appendChild(handle.element)
}

onMounted(() => {
  rebuild()
})

watch(
  () => [props.label, props.mode, props.size, props.disabled, props.block] as const,
  () => {
    // Minimal updates where possible
    if (!handle) {
      rebuild()
      return
    }

    handle.setLabel(props.label)
    handle.setDisabled(!!props.disabled)

    // Mode/size affect styles; simplest is rebuild when they change.
    // We detect changes via the watch list and just rebuild always.
    rebuild()
  }
)

onBeforeUnmount(() => {
  if (handle?.element?.parentNode) {
    handle.element.parentNode.removeChild(handle.element)
  }
  handle = null
})
</script>
