// .bkp/market/src/components/KwamiGlassButton.tsx
import { useEffect, useMemo, useRef } from 'react'
import { createGlassButton } from 'kwami/ui'

export function KwamiGlassButton(props: {
  label: string
  mode?: 'primary' | 'ghost' | 'outline'
  size?: 'sm' | 'md' | 'lg'
  disabled?: boolean
  block?: boolean
  onClick?: (event: MouseEvent) => void
}) {
  const mountRef = useRef<HTMLDivElement | null>(null)
  const handleRef = useRef<ReturnType<typeof createGlassButton> | null>(null)
  const key = useMemo(() => `${props.mode ?? 'primary'}:${props.size ?? 'md'}:${props.block ? '1' : '0'}`, [props.block, props.mode, props.size])

  useEffect(() => {
    const mount = mountRef.current
    if (!mount) return

    mount.innerHTML = ''
    handleRef.current?.element?.remove()

    const handle = createGlassButton({
      label: props.label,
      mode: props.mode ?? 'primary',
      size: props.size ?? 'md',
      disabled: !!props.disabled,
      onClick: (e) => props.onClick?.(e),
    })

    if (props.block) handle.element.style.width = '100%'

    handleRef.current = handle
    mount.appendChild(handle.element)

    return () => {
      handleRef.current?.element?.remove()
      handleRef.current = null
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key])

  useEffect(() => {
    handleRef.current?.setLabel(props.label)
    handleRef.current?.setDisabled(!!props.disabled)
  }, [props.disabled, props.label])

  return <div ref={mountRef} className={['inline-flex', props.block ? 'w-full' : ''].filter(Boolean).join(' ')} />
}

// dao/src/components/KwamiGlassButton.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy, onMount } from 'svelte'
  import { createGlassButton } from 'kwami/ui'

  export let label: string = 'Button'
  export let icon: string | undefined = undefined
  export let mode: 'primary' | 'ghost' | 'outline' = 'primary'
  export let size: 'sm' | 'md' | 'lg' = 'md'
  export let disabled: boolean = false
  export let className: string | undefined = undefined

  const dispatch = createEventDispatcher<{ click: MouseEvent }>()

  let host: HTMLDivElement | null = null
  let handle: ReturnType<typeof createGlassButton> | null = null

  onMount(() => {
    if (!host) return
    host.innerHTML = ''

    handle = createGlassButton({
      label,
      icon,
      mode,
      size,
      disabled,
      className,
      onClick: (e: MouseEvent) => dispatch('click', e),
    })

    host.appendChild(handle.element)
  })

  $: if (handle) {
    handle.setLabel(label)
    handle.setIcon(icon)
    handle.setDisabled(Boolean(disabled))
  }

  onDestroy(() => {
    handle?.element.remove()
    handle = null
  })
</script>

<div bind:this={host} class="inline-flex"></div>
