// market/src/components/WalletConnect.tsx
import { useEffect, useRef } from 'react'
import { createWalletConnectWidget, type WalletConnectWidgetHandle } from 'kwami/ui/wallet'
import { useWallet } from '@/state/wallet'

export function WalletConnect() {
  const mountRef = useRef<HTMLDivElement | null>(null)
  const widgetRef = useRef<WalletConnectWidgetHandle | null>(null)
  const { connector, refreshKwamiNfts } = useWallet()

  useEffect(() => {
    const mount = mountRef.current
    if (!mount) return

    widgetRef.current?.destroy()
    widgetRef.current = createWalletConnectWidget({
      connectLabel: 'Connect Wallet',
      showBalanceInButton: true,
      autoRefreshBalanceMs: 30_000,
      wallet: connector as any,
      onConnected: () => {
        void refreshKwamiNfts()
      },
      onAccountChange: () => {
        void refreshKwamiNfts()
      },
    })

    mount.innerHTML = ''
    mount.appendChild(widgetRef.current.element)

    return () => {
      widgetRef.current?.destroy()
      widgetRef.current = null
    }
  }, [connector, refreshKwamiNfts])

  return <div ref={mountRef} className="inline-flex items-center" />
}

// .bkp/dao/src/components/WalletConnect.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte'
  import { createWalletConnectWidget, type WalletConnectWidgetHandle } from 'kwami/ui/wallet'

  let host: HTMLDivElement | null = null
  let widget: WalletConnectWidgetHandle | null = null

  export async function open(): Promise<void> {
    await widget?.open()
  }

  export async function refresh(): Promise<void> {
    await widget?.refresh()
  }

  onMount(() => {
    if (!host) return
    host.innerHTML = ''

    widget = createWalletConnectWidget({
      connectLabel: 'Connect Wallet',
      showBalanceInButton: false,
      autoRefreshBalanceMs: 15_000,
      className: '',
    })

    host.appendChild(widget.element)
  })

  onDestroy(() => {
    widget?.destroy()
    widget = null
  })
</script>

<div bind:this={host} class="inline-flex items-center"></div>
